title: RPi OS
description: A Raspberry Pi System Download Site

repository: RPiOS/RPiOS.github.io

collections:
  Systems:
    output: true
    permalink: /System/:title.aspx

defaults:
  - scope:
      path: ""
      type: "Systems"
    values:
      layout: "post"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]